name: Push to PWS
on:
  push:
    branches: [ main ]
    paths-ignore:
        - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
        - '**.md'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Check PWS remote, pull, merge, and push
      env:
        PWS_URL: ${{ secrets.PWS_URL }}
      run: |
          # Pastikan kita berada di branch main
          git checkout main || git checkout -b main

          # Cek apakah remote PWS sudah ada, jika belum, tambahkan
          if ! git remote | grep -q "^pws$"; then
            git remote add pws $PWS_URL
          fi

          # Ambil perubahan terbaru dari remote PWS (branch master)
          git fetch pws master

          # Coba merge perubahan dari remote PWS (branch master)
          if ! git merge pws/master --no-edit; then
            echo "Terjadi konflik saat melakukan merge. Silakan selesaikan konflik secara manual."
            exit 1
          fi

          # Push ke remote PWS (branch master)
          if ! git push pws main:master; then
            echo "Error: Tidak dapat push perubahan. Silakan periksa pesan error di atas dan selesaikan konflik secara manual."
            exit 1
          fi
          echo "Push berhasil dilakukan ke PWS (branch master)."
